### ISSUE TITLE
登陆之后页面没有跳转

### ISSUE THREAD

**Issue by zhongxu-Sun** [yoyling/EPMS#1]
作者你好，我按照你给的使用说明运行成功了，数据库也建立了，但是登录成功之后页面没有跳转，后台报了一个这样的错误：
![image](https://user-images.githubusercontent.com/64886150/103332658-d47db700-4aa5-11eb-9808-4dd4a8bd62e9.png)

Exception in thread "AWT-EventQueue-0" org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
	at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:797)
	at dao.DeptDao.findDeptById(DeptDao.java:18)
	at view.MainFrame.initialize(MainFrame.java:496)
	at view.MainFrame.<init>(MainFrame.java:118)
         .....
能帮我看一下是什么原因吗？

**Comment by rawchen** [comment]
qq2221999792

**Comment by zzzzxxxccc** [comment]
作者你好，我按照你给的使用说明运行成功了，数据库也建立了，但是登录成功之后页面没有跳转，后台报了一个这样的错误：
Exception in thread "AWT-EventQueue-0" org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:797)
at dao.DeptDao.findDeptById(DeptDao.java:18)
at view.MainFrame.initialize(MainFrame.java:496)
at view.MainFrame.(MainFrame.java:118)
.....
能帮帮我看一下什么原因吗？谢谢

**Comment by zzzzxxxccc** [comment]
> 作者你好，我按照你给的使用说明运行成功了，数据库也建立了，但是登录成功之后页面没有跳转，后台报了一个这样的错误： ![image](https://user-images.githubusercontent.com/64886150/103332658-d47db700-4aa5-11eb-9808-4dd4a8bd62e9.png)
> 
> Exception in thread "AWT-EventQueue-0" org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0 at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71) at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:797) at dao.DeptDao.findDeptById(DeptDao.java:18) at view.MainFrame.initialize(MainFrame.java:496) at view.MainFrame.(MainFrame.java:118) ..... 能帮我看一下是什么原因吗？

什么原因啊
